
pretrained : "google/bert_uncased_L-2_H-128_A-2"
train_path: "/home/shared/MSO/image_train_test/full_dataset_chatbot/agency/train_with_images_one_image.csv"
test_path: "/home/shared/MSO/image_train_test/full_dataset_chatbot/agency/test_with_images_one_image.csv"
output_folder: "/home/shared/MSO/image_train_test/full_dataset_chatbot/agency/results/text_geolocs_bert_tiny/"
batch_size": 8
num_train_epochs: 9
learning_rate: 0.0008930676276027413
weight_decay: 0
warmup_steps: 0
max_seq_length: 210
text_field: cat_description
label_field: agency
# image_path_field: first_image_path
geoloc_start_index: 1
geoloc_end_index: 15
lr_scheduler: "linear"