
pretrained : "google/bert_uncased_L-2_H-128_A-2"
train_path: "/home/watsonchua/work/MSO_shared/image_train_test/full_dataset_chatbot/agency/with_object_detection_features/train.csv"
test_path: "/home/watsonchua/work/MSO_shared/image_train_test/full_dataset_chatbot/agency/with_object_detection_features/test.csv"
output_folder: "/home/shared/MSO/image_train_test/full_dataset_chatbot/agency/results/text_geolocs_one_image_objects_existence/"
batch_size: 16
num_train_epochs: 15
learning_rate: 2.0e-5
weight_decay: 0
warmup_steps: 0
max_seq_length: 210
text_field: cat_description
label_field: agency
# image_path_field: images_path
# using objects detected as "geolocs"
geoloc_start_index: 1
geoloc_end_index: 73
lr_scheduler: "linear"