
pretrained : "google/bert_uncased_L-2_H-128_A-2"
train_path: "/home/shared/MSO/image_train_test/full_dataset_chatbot/agency/train_with_images.csv"
test_path: "/home/shared/MSO/image_train_test/full_dataset_chatbot/agency/test_with_images.csv"
output_folder: "/home/shared/MSO/image_train_test/full_dataset_chatbot/agency/results/text_geolocs_bert_tiny/"
batch_size": 16
num_train_epochs: 20
learning_rate: 1.0e-5
weight_decay: 0.01
warmup_steps: 0
max_seq_length: 200
text_field: processed_description
label_field: agency
# image_path_field: image_paths
geoloc_start_index: 1
geoloc_end_index: 15
lr_scheduler: "cosine"